OBJDIR = build
SHLIB_EXT = so
SHLIB_FLAGS = -bundle -undefined dynamic_lookup
LA_LIBS = -framework Accelerate
LUA_INC = -I/Users/motohisa/working/lua-5.3.3/src
LUA_LIB = -L/Users/motohisa/working/lua-5.3.3/src -llua
LUA_MODULE_LIB =

CFLAGS += -O0 -Wall -g
CXXFLAGS += -O0 -Wall -std=c++11 -g

CC = cc
CXX = c++
