OBJDIR = build
SHLIB_EXT = so
SHLIB_FLAGS = -bundle -undefined dynamic_lookup
LA_LIBS = -framework Accelerate
LUA_INC = -I/Users/motohisa/working/lua-5.3.3/src -I/opt/local/include
LUA_LIB = -L/Users/motohisa/working/lua-5.3.3/src -llua -L/opt/local/lib -lfftw3
LUA_MODULE_LIB =

CFLAGS += -O0 -Wall -g3
# CFLAGS += -Wall
CXXFLAGS += -O0 -Wall -std=c++11 -g3 -DHAVE_LIBFFTW3 -ggdb -DENABLE_S4_TRACE
# CXXFLAGS += -Wall -std=c+11 -DHAVE_LIBFFTW3

CC = cc
CXX = c++
